- name: "reset cluster"
  hosts: k8s_cluster
  become: true
  tasks:
    - ansible.builtin.shell: |
        kubeadm reset --force

- name: "remove kube config"
  hosts: control_plane
  tasks:
    - name: "remove user config"
      ansible.builtin.shell: |
        rm -rf $HOME/.kube

    - name: "remove root config"
      become: true
      ansible.builtin.shell: |
        rm -rf $HOME/.kube
