control_plane:
  hosts:
    conduit:
      ansible_host: 192.168.1.10

worker_nodes:
  hosts:
    ontos:
      ansible_host: 192.168.1.11
    pneuma:
      ansible_host: 192.168.1.12
    logos:
      ansible_host: 192.168.1.13

k8s_cluster:
  children:
    control_plane:
    worker_nodes:

